version: "2"
services:
  chat:
    build: .
    ports:
        - "3000:3000"
    environment:
        - MONGO_URL='mongodb://mongo:27017/admin'
        - URL='https://3000-dot-6910560-dot-devshell.appspot.com/'
    volumes:
        - .:/usr/app
    depends_on:
        - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
