version: "2"
services:
  chat:
    build: .
    ports:
        - "5000:5000"
    environment:
        - MONGO_URL='mongodb://mongo:27017/admin'
        - URL=https://5000-cs-361250610342-default.us-east1.cloudshell.dev
        - PORT=5000
    volumes:
        - .:/usr/app
    depends_on:
        - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
