# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        env:
          CI: true
      - uses: actions/checkout@v1
      - name: Artifact
      - run: mkdir -p build/artifact
      - run: npm audit --json > build/artifact/audit.json
      - uses: actions/upload-artifact@v1
        with:
          name: audit
          path: build/artifact
      - name: Node Code Formatter
      - uses: MarvinJWendt/run-node-formatter@1.5.2
