# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      env:
        CI: true
  artifacts:
    name: artifact
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
      - shell: bash
        run: |
          npm audit --json > artifact.json
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: artifacts/audit.json
  quality:
     name: quality
     needs: artifacts
     runs-on: ubuntu-latest
     steps:
        - name: Node Code Formatter
          uses: MarvinJWendt/run-node-formatter@1.5.2
