# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Cache
        uses: actions/cache@v1.2.0
        with: 
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
            
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
            node-version: ${{ matrix.node-version }}
            name: audit
            path: build/artifact
     
      - name: Node Code Formatter
        uses: MarvinJWendt/run-node-formatter@1.5.2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node-version }}
 
      - name: npm install, build, and test
        run: |
          npm ci
          npm install
          mkdir -p build/artifact && npm audit --json > build/artifact/audit.json
          npm start
        env:
          CI: true
